#!/bin/sh
#MISE description="pi를 YoloBox 샌드박스에서 실행"
exec yolobox \
  --mount "$HOME/.pi/agent:/home/yolo/.pi/agent" \
  --mount "$(npm root -g):/home/yolo/.npm-global/lib/node_modules" \
  --env NPM_CONFIG_PREFIX=/home/yolo/.npm-global \
  --env PI_AUTORUN=1
