#!/bin/sh
#MISE description="pi를 YoloBox 샌드박스에서 실행. --version x.y.z 로 pi 버전 일회성 지정 가능"

# --version 플래그 파싱
PI_VERSION=""
while [ $# -gt 0 ]; do
  case "$1" in
    --version) PI_VERSION="$2"; shift 2 ;;
    *) shift ;;
  esac
done

if [ -n "$PI_VERSION" ]; then
  TMPFILE=$(mktemp /tmp/yolobox-pi-XXXXXX.Dockerfile)
  cat > "$TMPFILE" << EOF
USER root
RUN npm install -g --prefix /usr/local @earendil-works/pi-coding-agent@${PI_VERSION}
RUN echo 'if [ -n "\$PI_AUTORUN" ]; then exec pi; fi' >> /etc/bash.bashrc
USER yolo
EOF
  echo "[pi] Using version override: $PI_VERSION (temp Dockerfile: $TMPFILE)"
  exec yolobox \
    --customize-file "$TMPFILE" \
    --mount "$HOME/.pi/agent:/home/yolo/.pi/agent" \
    --mount "$(npm root -g):/home/yolo/.npm-global/lib/node_modules" \
    --env NPM_CONFIG_PREFIX=/home/yolo/.npm-global \
    --env PI_AUTORUN=1
fi

exec yolobox \
  --mount "$HOME/.pi/agent:/home/yolo/.pi/agent" \
  --mount "$(npm root -g):/home/yolo/.npm-global/lib/node_modules" \
  --env NPM_CONFIG_PREFIX=/home/yolo/.npm-global \
  --env PI_AUTORUN=1
